variables:
  DEPLOY_ENVIRONMENT: "null"


include:
  - project:
      nocacuk/BODC/software/gitlab_runners
    ref: master
    file: v2/python.gitlab-ci.yml

  - project:
      nocacuk/BODC/software/gitlab_runners
    ref: master
    file: v2/bodc.gitlab-ci.yml

  - project:
      nocacuk/BODC/software/gitlab_runners
    ref: master
    file: v2/semver-tags.gitlab-ci.yml

  - project:
      nocacuk/BODC/software/gitlab_runners
    ref: master
    file: v2/cruft.gitlab-ci.yml


# The 4 jobs below are inherited from the base runners, to append a job to any of the stages you can
# add a 'script:' block underneath the 'extends' block, this will run after the inherited job has finished.
# To aid in development, a small summary of the inherited job is included.


# The test commands seen under the testenv section are executed.
test:
  extends:
   - .python-test

# The linting commands seen under the testenv:lint section are executed.
lint:
  extends:
   - .python-lint

# 'poetry build' is executed to build wheel and tar file.
build:
  extends:
   - .python-build

# File is uploaded to PyPi for any valid release tag.
upload:
  extends:
   - .python-upload

# Run Cruft to re-align projects to Cookiecutter.
cruft-template-check:
  extends: .cruft_check_update
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
