name: Build and publish the package to PyPi

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
        poetry build
    - name: Upload artifacts for downstream jobs
      uses: actions/upload-artifact@v4
      with:
        name: releases
        path: dist
    # - name: Publish
    #   env:
    #     PYPI_TOKEN: ${{ secrets.PYPI-TOKEN }}
    #   run: |
    #     poetry config pypi-token.pypi "$PYPI_TOKEN"
    #     poetry build
    #     poetry publish
