name: Build and publish the package to PyPi

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install poetry twine
        poetry install --no-root
        poetry build
    - name: Check built artifacts
      run: |
        if [ ! -d dist ] || [ -z "$(ls -A dist)" ]; then
          echo "❌ Build failed: dist/ is empty or missing"
          exit 1
        fi
        python -m twine check dist/*
        echo "✅ Artifacts look good"
        ls -la dist
    - name: Upload artifacts for downstream jobs
      uses: actions/upload-artifact@v4
      with:
        name: releases
        path: dist

  upload-to-pypi:
    needs: build-artifacts
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
          skip-existing: false
          repository-url: https://upload.pypi.org/legacy/
