name: Build and publish the package to PyPi

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
        poetry build
    - name: Upload artifacts for downstream jobs
      uses: actions/upload-artifact@v4
      with:
        name: releases
        path: dist

  upload-to-pypi:
    needs: build-artifacts
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist

      - name: Publish package to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config pypi-token.pypi "$PYPI_TOKEN"
          poetry publish
